# Define your workflow name, triggers, and jobs
name: Build and deploy Python app to Azure Web App - Star-Segmentor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Add your steps for setting up Python, creating a virtual environment, installing dependencies, etc.

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip
          # Additional paths if needed
          
      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Download and unzip release
        run: |
          wget https://github.com/Puneet-Bajaj-IITM/image-segmentation/releases/download/results.zip
          unzip -o results.zip -d ${{ github.workspace }}/results
          ls
          pwd
        working-directory: ${{ github.workspace }}

      - name: Install dependencies
        run: pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
        
     
      # Additional steps like running model.py, setting permissions, etc.

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Star-Segmentor'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6A4D988E5AEA4B01BFC476E6E84677AF }}



  run-app:
    needs:
      - build
      - deploy
    runs-on: ubuntu-latest

    steps:
     
      - name: Run Python app
        run: python /home/runner/work/image-segmentation/image-segmentation/app.py
        working-directory: ${{ github.workspace }}
